version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: superagent
    versions:
    - "> 5.3.1"
  - dependency-name: eslint-config-prettier
    versions:
    - 8.0.0
    - 8.1.0
    - 8.2.0
  - dependency-name: eslint-plugin-flowtype
    versions:
    - 5.7.1
  - dependency-name: flow-bin
    versions:
    - 0.143.1
    - 0.144.0
    - 0.145.0
    - 0.149.0
  - dependency-name: "@babel/core"
    versions:
    - 7.13.13
  - dependency-name: husky
    versions:
    - 5.0.9
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
  - dependency-name: "@babel/plugin-proposal-class-properties"
    versions:
    - 7.12.13
